[project]
name = "atlas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mikelor", email = "mikelor@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "huggingface-hub>=1.32.0",
    "onnx>=1.23.0",
    "onnxruntime-genai>=0.16.0",
    "onnxruntime-qnn>=2.6.0",
    "qai-hub-models-cli>=0.62.2",
]

[project.scripts]
atlas = "atlas:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
